name: Generate Snake Animation and README

on:
  schedule: # Execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main  # Change this to 'master' if your main branch is named 'master'

jobs:
  generate:
    permissions:
      contents: write  # Grants write permissions for this job
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository

      - name: Generate snake.svg
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}  # Uses the owner of the repository
          outputs: dist/snake.svg  # Generates the snake SVG with dark palette

      - name: Add snake.svg to README
        run: |
          echo "![snake gif](./dist/snake.svg)" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Update README with snake animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
