name: Generate Snake Animation

on:
  schedule:
    # Run the workflow every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:  # Manual trigger

  push:
    branches:
      - master  # Ensure this is the branch where you want the workflow to trigger

jobs:
  generate:
    permissions:
      contents: write  # Grant write permission
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Generate the snake.svg
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Replace with your GitHub username
          outputs: dist/snake.svg?palette=github-dark  # Ensure this path is correct

      # List files in the output directory (debugging step)
      - name: List output files
        run: ls -R dist

      # Push the generated snake.svg to the output branch
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Branch to push to
          build_dir: dist  # Directory containing snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
