name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *' # Run daily
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate contribution snake
        uses: platane/snk@v2.0.0
        with:
          github_user_name: OliviaGG   # Change this line
          outputs: output/github-contribution-grid-snake.svg   # Add this line
          dark_svg_out: output/github-contribution-grid-snake-dark.svg   # If valid
