name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Generate Snake Game from Contributions
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: YOUR_USERNAME
          outputs: svg
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Upload Snake Game to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: snake-game
          path: dist
